### ISSUE TITLE
ReflectionException in Container.php line 749: Class sweet-flash does not exist

### ISSUE THREAD

**Issue by PsKs** [faustbrian/Laravel-Sweet-Flash#4]
Hello, I install this package form composer in Laravel 5.3
and I follow  guidelines for implement this package.
But error 
`ReflectionException in Container.php line 749: Class sweet-flash does not exist`
can i mistake config?

I use `BrianFaust\SweetFlash\ServiceProvider::class` instead `BrianFaust\SweetFlash\SweetFlashServiceProvider::class` Becuase PhpStorm show `Undefined class SweetFlashServiceProvider`

**Comment by XnCN** [comment]
How did you fix it i'm having the same problem

**Comment by PsKs** [comment]
@XnCN I move to [sweet-alert](https://github.com/uxweb/sweet-alert) but I got the same problem. And I use `php artisan config:cache` to fix that.
This is my issues in sweet-alert [link](https://github.com/uxweb/sweet-alert/issues/42)

**Comment by XnCN** [comment]
@PsKs  you are a man! thank you for comment it work , php artisan config:cache :)
